### ISSUE TITLE
Update for latest Gleam HTTP

### ISSUE THREAD

**Issue by lpil** [gleam-lang/fetch#2]

**Comment by pascalwengerter** [comment]
Has been addressed via https://github.com/gleam-lang/fetch/commit/2b0bef9ad5d6f7d7b9cbf70f1baf11eafb874f3a#diff-689de4eb7138dfad05731654b00ade84177ef0d184b8f862378b0f258560848b ? :)

**Comment by lpil** [comment]
Yes! Thank you
